"""Added availability

Revision ID: 27a0c99b5b90
Revises: b7fcb7e9050a
Create Date: 2023-07-06 18:10:27.537949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a0c99b5b90'
down_revision = 'b7fcb7e9050a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Availability_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Availability_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_Availability_start_time'), ['start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Availability_start_time'))
        batch_op.drop_index(batch_op.f('ix_Availability_end_time'))
        batch_op.drop_index(batch_op.f('ix_Availability_artist_id'))

    op.drop_table('Availability')
    # ### end Alembic commands ###
