"""Venue Show relationship 1

Revision ID: 482b0b62ee84
Revises: 40a36796073c
Create Date: 2023-06-15 12:24:49.306068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482b0b62ee84'
down_revision = '40a36796073c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Artist', ['artist_id'], ['id'])
        batch_op.create_foreign_key(None, 'Venue', ['venue_id'], ['id'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
