"""Changed availability to TIME

Revision ID: 8032d3fe05af
Revises: 27a0c99b5b90
Create Date: 2023-07-07 10:14:10.132384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8032d3fe05af'
down_revision = '27a0c99b5b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Availability', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIME(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIME(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Availability', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIME(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIME(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###
