"""Added nav porperties to Show

Revision ID: 88ed54a3d08d
Revises: a2c7e72dcad6
Create Date: 2023-06-17 17:10:44.503353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ed54a3d08d'
down_revision = 'a2c7e72dcad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
