"""Initial

Revision ID: b7fcb7e9050a
Revises: 
Create Date: 2023-07-03 10:01:47.741263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7fcb7e9050a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=36), nullable=False),
    sa.Column('image_link', sa.String(length=500), server_default='https://loremflickr.com/320/240/band/all', nullable=False),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String(length=24)), nullable=False),
    sa.Column('website_link', sa.String(length=120), nullable=False),
    sa.Column('seeking_venue', sa.Boolean(), nullable=False),
    sa.Column('seeking_description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Artist_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_Artist_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_Artist_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_Artist_state'), ['state'], unique=False)

    op.create_table('Venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=36), nullable=False),
    sa.Column('image_link', sa.String(length=500), server_default='https://loremflickr.com/320/240/music,bar/all', nullable=False),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String(length=24)), nullable=False),
    sa.Column('website_link', sa.String(length=120), nullable=False),
    sa.Column('seeking_talent', sa.Boolean(), nullable=False),
    sa.Column('seeking_description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Venue_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_Venue_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_Venue_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_Venue_state'), ['state'], unique=False)

    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'artist_id', 'start_time', name='venue_artist_time_idx')
    )
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Show_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Show_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_Show_venue_id'), ['venue_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Show', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Show_venue_id'))
        batch_op.drop_index(batch_op.f('ix_Show_start_time'))
        batch_op.drop_index(batch_op.f('ix_Show_artist_id'))

    op.drop_table('Show')
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Venue_state'))
        batch_op.drop_index(batch_op.f('ix_Venue_name'))
        batch_op.drop_index(batch_op.f('ix_Venue_created_at'))
        batch_op.drop_index(batch_op.f('ix_Venue_city'))

    op.drop_table('Venue')
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Artist_state'))
        batch_op.drop_index(batch_op.f('ix_Artist_name'))
        batch_op.drop_index(batch_op.f('ix_Artist_created_at'))
        batch_op.drop_index(batch_op.f('ix_Artist_city'))

    op.drop_table('Artist')
    # ### end Alembic commands ###
