"""Changed availability to include creation time

Revision ID: f9183ffaece7
Revises: 8032d3fe05af
Create Date: 2023-07-08 15:54:42.011277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9183ffaece7'
down_revision = '8032d3fe05af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.create_index(batch_op.f('ix_Availability_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Availability_created_at'))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
